// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Server;

import Client.Register;

/**
 * Classe que guarda a permissão de registo no servidor 
 * @author Utilizador
 */
public class RegisterRequest {
	
	/**
	 * Atributo que guarda a informação de registo do cliente
	 */
	private Register register;

	/**
	 * Construtor da classe
	 * @param register Register com a informação de registo
	 */
	public RegisterRequest(Register register) {
		super();
		this.register = register;
	}

	/**
	 * Método para obter a informação de registo
	 * @return Register com a informação de registo
	 */
	public Register getRegister() {
		return register;
	}

	/**
	 * Método para atribuir a informação de registo
	 * @param register Register com a informação de registo
	 */
	public void setRegister(Register register) {
		this.register = register;
	}

	/**
	 * Método para verificar se o registo foi feito com sucesso
	 * @return success true caso o registo tenha sido feito com sucesso
	 */
	public Boolean regist() {
		return true;
	}
};
