// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package server;

import client.Register;

/**
 * Classe que guarda a permiss�o de registo no servidor 
 * @author Utilizador
 */
public class RegisterRequest {
	
	/**
	 * Atributo que guarda a informa��o de registo do cliente
	 */
	private Register register;

	/**
	 * Construtor da classe
	 * @param register Register com a informa��o de registo
	 */
	public RegisterRequest(Register register) {
		super();
		this.register = register;
	}

	/**
	 * M�todo para obter a informa��o de registo
	 * @return Register com a informa��o de registo
	 */
	public Register getRegister() {
		return register;
	}

	/**
	 * M�todo para atribuir a informa��o de registo
	 * @param register Register com a informa��o de registo
	 */
	public void setRegister(Register register) {
		this.register = register;
	}

	/**
	 * M�todo para verificar se o registo foi feito com sucesso
	 * @return success true caso o registo tenha sido feito com sucesso
	 */
	public Boolean regist() {
		return true;
	}
};
