<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RootElement" nsURI="http:///RootElement.ecore" nsPrefix="RootElement">
  <eSubpackages name="Server" nsURI="http:///RootElement/Server.ecore" nsPrefix="RootElement.Server">
    <eClassifiers xsi:type="ecore:EClass" name="AcceptClients">
      <eOperations name="accepted" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="userdata" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReceiveMessageRequest">
      <eOperations name="received" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false"
          lowerBound="1" eType="#//Client/SendMessage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="userdata" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sendmessagerequest" ordered="false"
          lowerBound="1" eType="#//Server/SendMessageRequest"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SendMessageRequest">
      <eOperations name="sent" ordered="false" lowerBound="1">
        <eParameters name="success" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false"
          lowerBound="1" eType="#//Client/SendMessage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="userdata" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivemessage" ordered="false"
          lowerBound="1" eType="#//Client/ReceiveMessage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RegisterRequest">
      <eOperations name="regist" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false"
          lowerBound="1" eType="#//Client/Register"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="register" ordered="false"
          lowerBound="1" eType="#//Client/Register"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogInRequest">
      <eOperations name="logInAccepted" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" ordered="false"
          lowerBound="1" eType="#//Client/LogIn"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="login" ordered="false"
          lowerBound="1" eType="#//Client/LogIn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SQLInformations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="onlineUsers" ordered="false"
          upperBound="-1" eType="#//Client/UserData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="userdata" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Client" nsURI="http:///RootElement/Client.ecore" nsPrefix="RootElement.Client">
    <eClassifiers xsi:type="ecore:EClass" name="Register">
      <eOperations name="RegisterRequest" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogIn">
      <eOperations name="LogInRequest" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SendMessage">
      <eOperations name="send" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="friend" ordered="false"
          lowerBound="1" eType="#//Client/FriendData"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivemessagerequest"
          ordered="false" lowerBound="1" eType="#//Server/ReceiveMessageRequest"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FriendData">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivemessage" ordered="false"
          lowerBound="1" eType="#//Client/ReceiveMessage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sendmessage" ordered="false"
          lowerBound="1" eType="#//Client/SendMessage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="friends" ordered="false"
          upperBound="-1" eType="#//Client/Friends"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReceiveMessage">
      <eOperations name="receive" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="friend" ordered="false"
          lowerBound="1" eType="#//Client/FriendData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Friends">
      <eOperations name="addFriend" ordered="false" lowerBound="1">
        <eParameters name="friend" ordered="false" lowerBound="1" eType="#//Client/FriendData"/>
      </eOperations>
      <eOperations name="removeFriend" ordered="false" lowerBound="1">
        <eParameters name="friend" ordered="false" lowerBound="1" eType="#//Client/FriendData"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="friendsList" ordered="false"
          upperBound="-1" eType="#//Client/FriendData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogOut">
      <eOperations name="logOutRequest" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false"
          lowerBound="1" eType="#//Client/UserData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class1"/>
    <eClassifiers xsi:type="ecore:EClass" name="UserData">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logout" ordered="false"
          lowerBound="1" eType="#//Client/LogOut"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="login" ordered="false"
          lowerBound="1" eType="#//Client/LogIn"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="register" ordered="false"
          lowerBound="1" eType="#//Client/Register"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="GUI" nsURI="http:///RootElement/GUI.ecore" nsPrefix="RootElement.GUI"/>
</ecore:EPackage>
